# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cd6696504fe0eac3fcf152fed0d96d93"
name = "ic-nft-creater"
application_url = "https://bikes-families-terrain-webshots.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ic-nft.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_customers, write_customers, read_files, write_files, read_themes, write_themes, write_gift_cards, read_gift_cards"

[auth]
redirect_urls = [
  "https://bikes-families-terrain-webshots.trycloudflare.com/auth/callback",
  "https://bikes-families-terrain-webshots.trycloudflare.com/auth/shopify/callback",
  "https://bikes-families-terrain-webshots.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
