# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ic-nft-creater"
client_id = "15957d22030f9d24ce2357cea5cdd97a"
application_url = "https://receivers-organizing-b-numerous.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://receivers-organizing-b-numerous.trycloudflare.com/auth/callback",
  "https://receivers-organizing-b-numerous.trycloudflare.com/auth/shopify/callback",
  "https://receivers-organizing-b-numerous.trycloudflare.com/api/auth/callback",
  "https://receivers-organizing-b-numerous.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ic-nft.myshopify.com"
