# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ic-nft-creater"
client_id = "cd6696504fe0eac3fcf152fed0d96d93"
application_url = "https://societies-mixed-enormous-scenarios.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_customers, write_customers"

[auth]
redirect_urls = [
  "https://societies-mixed-enormous-scenarios.trycloudflare.com/auth/callback",
  "https://societies-mixed-enormous-scenarios.trycloudflare.com/auth/shopify/callback",
  "https://societies-mixed-enormous-scenarios.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ic-nft.myshopify.com"
